quiz_questions_list = [
    {"ask_question": "The Earth is flat.", "the_answer": "False"},
    {"ask_question": "Water boils at 100 degrees Celsius at sea level.", "the_answer": "True"},
    {"ask_question": "Mars is the largest planet in our solar system.", "the_answer": "False"},
    {"ask_question": "Photosynthesis is the process by which plants convert light into energy.", "the_answer": "True"},
    {"ask_question": "Albert Einstein discovered gravity.", "the_answer": "False"},
    {"ask_question": "The chemical symbol for gold is 'Go'.", "the_answer": "False"},
    {"ask_question": "The human body has four lungs.", "the_answer": "False"},
    {"ask_question": "Oxygen is the most abundant element in the Earth's atmosphere.", "the_answer": "False"},
    {"ask_question": "The primary colors of light are red, green, and blue.", "the_answer": "True"},
    {"ask_question": "Spiders are insects.", "the_answer": "False"},
    {"ask_question": "The Great Wall of China is visible from space.", "the_answer": "False"},
    {"ask_question": "A right triangle can have two equal-length sides.", "the_answer": "False"},
    {"ask_question": "Bananas are berries.", "the_answer": "True"},
    {"ask_question": "The capital of Japan is Beijing.", "the_answer": "False"},
    {"ask_question": "Diamonds are made from compressed coal.", "the_answer": "False"},
    {"ask_question": "The sun is a star.", "the_answer": "True"},
    {"ask_question": "Rabbits are rodents.", "the_answer": "False"},
    {"ask_question": "The chemical symbol for silver is 'Ag'.", "the_answer": "True"},
    {"ask_question": "Mount Everest is the tallest mountain in the world.", "the_answer": "True"},
    {"ask_question": "The human body has 206 bones.", "the_answer": "True"},
    {"ask_question": "Sound travels faster in water than in air.", "the_answer": "True"},
    {"ask_question": "The currency of France is the Franc.", "the_answer": "False"},
    {"ask_question": "An octopus has three hearts.", "the_answer": "True"},
    {"ask_question": "Polar bears are only found in Antarctica.", "the_answer": "False"}
    # Add more questions as needed
]
